### ISSUE TITLE
The comment in Math.js confuses me.

### ISSUE THREAD

**Issue by IBMUser1** [IBMGitDemo/GithubDemo#4]
Not sure if the math in there is right. It tells me it's all wrong and is asking where I went to school...

**Comment by AKippins** [comment]
Hey @IBMTester2. Could you take a look at Math.js when you get a chance?

**Comment by AKippins** [comment]
Hey @IBMDev3. Can you take a look at @IBMTester2's comment and fix the issue.

**Comment by AKippins** [comment]
Issue fixed please refer to Math.js
